---
    name: Klickhouse Example - Deploy
    
    on:
      workflow_dispatch:
    
    permissions:
      contents: read
      packages: write
    
    jobs:
      converge:
        runs-on: deploy
        steps:
        - uses: actions/checkout@v4
    
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            install: true
            driver-opts: image=moby/buildkit:latest
            buildkitd-flags: --debug
        
        - name: Cache Werf Stages
          uses: actions/cache@v4
          with:
            path: ~/.werf/local_cache
            key: ${{ runner.os }}-werf-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-werf-
    
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    
        - name: Converge
          uses: werf/actions/converge@v2
          with:
            env: production
            kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
          env:
            WERF_REPO: ghcr.io/katanacap/klickhouse-example
            WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}
            DOCKER_BUILDKIT: 1
            WERF_LOG_VERBOSE: "on"
            WERF_DOCKER_SERVER_STORAGE_DRIVER: overlay2
            WERF_BUILDAH_MODE: auto
            